import { create } from "zustand"

export const useStore = create((set, get) => ({
  gridSize: 4,
  difficulty: "medium",
  grid: [],
  agentPos: { x: 0, y: 0 },
  agentDir: "east",
  logs: [],
  kbFacts: [],
  running: false,
  gameOver: false,
  gameWon: false,
  speed: 500,
  steps: 0,
  inferences: 0,
  resolutions: 0,
  cellsExplored: 0,
  showHeatmap: false,
  voiceEnabled: false,
  history: [],
  hasArrow: true,
  score: 0,
  startTime: null,
  elapsed: 0,

  setGrid: (grid) => set({ grid }),
  setAgentPos: (pos) => set({ agentPos: pos }),
  addLog: (log) =>
    set((state) => ({
      logs: [{ text: log.text, type: log.type || "info", ts: Date.now() }, ...state.logs].slice(0, 200),
    })),
  addKbFact: (fact) =>
    set((state) => ({
      kbFacts: state.kbFacts.includes(fact) ? state.kbFacts : [...state.kbFacts, fact],
    })),
  setRunning: (val) => set({ running: val }),
  setSpeed: (speed) => set({ speed }),
  setDifficulty: (difficulty) => set({ difficulty }),
  setGridSize: (gridSize) => set({ gridSize }),
  toggleHeatmap: () => set((s) => ({ showHeatmap: !s.showHeatmap })),
  toggleVoice: () => set((s) => ({ voiceEnabled: !s.voiceEnabled })),
  incrementInferences: () => set((s) => ({ inferences: s.inferences + 1 })),
  incrementResolutions: () => set((s) => ({ resolutions: s.resolutions + 1 })),
  incrementSteps: () => set((s) => ({ steps: s.steps + 1 })),
  incrementExplored: () => set((s) => ({ cellsExplored: s.cellsExplored + 1 })),
  addScore: (pts) => set((s) => ({ score: s.score + pts })),
  setGameOver: (val) => set({ gameOver: val, running: false }),
  setGameWon: (val) => set({ gameWon: val, running: false }),
  pushHistory: (snapshot) =>
    set((state) => ({ history: [...state.history, snapshot] })),
  setElapsed: (elapsed) => set({ elapsed }),
  setStartTime: (t) => set({ startTime: t }),

  resetAll: () =>
    set({
      grid: [],
      agentPos: { x: 0, y: 0 },
      agentDir: "east",
      logs: [],
      kbFacts: [],
      running: false,
      gameOver: false,
      gameWon: false,
      steps: 0,
      inferences: 0,
      resolutions: 0,
      cellsExplored: 0,
      history: [],
      hasArrow: true,
      score: 0,
      startTime: null,
      elapsed: 0,
    }),
}))
